version: "3.9"

networks:
  default:
    name: neshast-app-net
    driver: bridge

services:
  app:
    container_name: neshast-app-app
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    image: neshast/nestjs-base:latest
    restart: always
    env_file:
      - ./.env
    networks:
      - default
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/opt
      - ./docker/storage:${APP_STORAGE_PATH}:rw
    working_dir: /opt
    depends_on:
      - db_mongo
      - db_redis
    command: yarn start:dev

  db_mongo:
    container_name: neshast-app-db-mongo
    image: mongo:6.0.3
    restart: always
    hostname: ${MONGO_HOSTNAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - default
    volumes:
      - ./docker/volumes/db_mongo/data:/data/db:rw
      - ./docker/db_mongo_initdb.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo_express:
    container_name: neshast-app-db-mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
    networks:
      - default
    ports:
      - 8081:8081
    depends_on:
      - db_mongo

  db_redis:
    container_name: neshast-app-db-redis
    image: redis:7.0.8-alpine
    restart: always
    hostname: ${REDIS_HOSTNAME}
    networks:
      - default
    volumes:
      - ./docker/volumes/db_redis/data:/data:rw